name: TEST Apply New Account Baseline

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: "A distinct ID for this workflow run"
        required: true
        type: string
      branch:
        description: "The branch in infra-live-central in which to run the terragrunt command"
        required: true
        type: string
      working_directory:
        description: "The folder path in which terragrunt should be run"
        required: true
        type: string
      management_account:
        description: "The AWS Account ID of the Control Tower Management Account"
        required: true
        type: string
      child_account:
        description: "The AWS Account ID of the account we're operating in"
        required: true
        type: string
      terragrunt_command:
        type: string
        description: "The terragrunt command to run"
        required: true
        default: "plan"
      infra_live_repo:
        type: string
        description: "The infrastructure live repo on which to run terragrunt"
        required: true
      presigned_caller_identity:
        description: "The presigned URL sent by the calling account"
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        env:
          DISTINCT_ID: ${{ github.event.inputs.distinct_id }}
        run: echo "$DISTINCT_ID"

      - name: Test Expected Inputs
        env:
          BRANCH: ${{ inputs.branch }}
          INFRA_LIVE_REPO: ${{ inputs.infra_live_repo }}
          WORKING_DIRECTORY: ${{ inputs.working_directory }}
          TERRAGRUNT_COMMAND: ${{ inputs.terragrunt_command }}
          MANAGEMENT_ACCOUNT: ${{ inputs.management_account }}
          CHILD_ACCOUNT: ${{ inputs.child_account }}
          PRESIGNED_CALLER_IDENTITY: ${{ inputs.presigned_caller_identity }}
        run: |
          # Required Inputs
          echo "BRANCH: $BRANCH"
          echo "INFRA_LIVE_REPO: $INFRA_LIVE_REPO"
          echo "WORKING_DIRECTORY: $WORKING_DIRECTORY"
          echo "TERRAGRUNT_COMMAND: $TERRAGRUNT_COMMAND"
          echo "MANAGEMENT_ACCOUNT: $MANAGEMENT_ACCOUNT"
          echo "CHILD_ACCOUNT: $CHILD_ACCOUNT"

          if [[ ${PRESIGNED_CALLER_IDENTITY:-} != "fake token" ]]; then
            echo "Did not receive expected presigned caller identity"
            exit 1
          fi
