name: TEST Apply New Account Baseline

on:
    workflow_dispatch:
      inputs:
          branch:
            description: "The branch in infra-live-central in which to run the terragrunt command"
            required: true
            type: string
          working_directory:
            description: "The folder path in which terragrunt should be run"
            required: true
            type: string
          management_account:
            description: "The AWS Account ID of the Control Tower Management Account"
            required: true
            type: string
          child_account:
            description: "The AWS Account ID of the account we're operating in"
            required: true
            type: string
          terragrunt_command:
            type: string
            description: "The terragrunt command to run"
            required: true
            default: "plan"
          infra_live_repo:
            type: string
            description: "The infrastructure live repo on which to run terragrunt"
            required: true

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - name: Test Expected Inputs
          env:
            BRANCH: ${{ inputs.branch }}
            INFRA_LIVE_REPO: ${{ inputs.infra_live_repo }}
            WORKING_DIRECTORY: ${{ inputs.working_directory }}
            TERRAGRUNT_COMMAND: ${{ inputs.terragrunt_command }}
            MANAGEMENT_ACCOUNT: ${{ inputs.management_account }}
            CHILD_ACCOUNT: ${{ inputs.child_account }}
          run: |
            # Required Inputs
            echo "BRANCH: $BRANCH"
            echo "INFRA_LIVE_REPO: $INFRA_LIVE_REPO"
            echo "WORKING_DIRECTORY: $WORKING_DIRECTORY"
            echo "TERRAGRUNT_COMMAND: $TERRAGRUNT_COMMAND"
            echo "MANAGEMENT_ACCOUNT: $MANAGEMENT_ACCOUNT"
            echo "CHILD_ACCOUNT: $CHILD_ACCOUNT"
