name: TEST Create Account and Generate Baselines

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: "A distinct ID for this workflow run"
        required: true
        type: string
      management_account:
        description: "Management Account"
        required: true
      new_account_name:
        description: "New Account Name"
        required: true
      branch:
        description: "Branch"
        required: true
      infra_live_repo:
        description: "Infra Live Repo"
        required: true
      working_directory:
        description: "Working Directory"
        required: true
      terragrunt_command:
        description: "Terragrunt Command"
        required: true
      presigned_caller_identity:
        description: "The presigned URL sent by the calling account"
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        env:
          DISTINCT_ID: ${{ github.event.inputs.distinct_id }}
        run: echo "$DISTINCT_ID"

      - name: Test Expected Inputs
        env:
          BRANCH: ${{ inputs.branch }}
          INFRA_LIVE_REPO: ${{ inputs.infra_live_repo }}
          WORKING_DIRECTORY: ${{ inputs.working_directory }}
          TERRAGRUNT_COMMAND: ${{ inputs.terragrunt_command }}
          MANAGEMENT_ACCOUNT: ${{ inputs.management_account }}
          NEW_ACCOUNT_NAME: ${{ inputs.new_account_name }}
          PRESIGNED_CALLER_IDENTITY: ${{ inputs.presigned_caller_identity }}
        run: |
          # These verify the expected values sent by the workflow dispatch to this workflow in `infrastructure-pipelines`
          # When `pipelines-dispatch` is called with the values found in `test-caller.yml`.

          if [[ $MANAGEMENT_ACCOUNT != "123" ]]; then
            echo "MANAGEMENT_ACCOUNT is not set to expected value"
            exit 1
          fi

          if [[ $NEW_ACCOUNT_NAME != "new_account_name" ]]; then
            echo "NEW_ACCOUNT_NAME is not set to expected value"
            exit 1
          fi

          if [[ -z $BRANCH ]]; then
            echo "BRANCH is not set"
            exit 1
          fi

          if [[ $INFRA_LIVE_REPO != "gruntwork-io/pipelines-dispatch" ]]; then
            echo "INFRA_LIVE_REPO is not set to expected value"
            exit 1
          fi

          if [[ $WORKING_DIRECTORY != "." ]]; then
            echo "WORKING_DIRECTORY is not set to expected value"
            exit 1
          fi

          if [[ $TERRAGRUNT_COMMAND != "command args" ]]; then
            echo "TERRAGRUNT_COMMAND is not set to expected value"
            exit 1
          fi

          if [[ -z ${PRESIGNED_CALLER_IDENTITY:-} ]]; then
            echo "PRESIGNED_CALLER_IDENTITY is not set, which is expected when `presign_token` is `true` in `pipelines-dispatch`"
            exit 0
          fi

          if [[ ${PRESIGNED_CALLER_IDENTITY} != "fake token" ]]; then
            echo "Did not receive expected presigned caller identity, which is expected when `presign_token` is `true` in `pipelines-dispatch`"
            exit 1
          fi
