name: TEST Create Account and Generate Baselines

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: "A distinct ID for this workflow run"
        required: true
        type: string
      management_account:
        description: "Management Account"
        required: true
      new_account_name:
        description: "New Account Name"
        required: true
      branch:
        description: "Branch"
        required: true
      infra_live_repo:
        description: "Infra Live Repo"
        required: true
      working_directory:
        description: "Working Directory"
        required: true
      terragrunt_command:
        description: "Terragrunt Command"
        required: true
      presigned_caller_identity:
        description: "The presigned URL sent by the calling account"
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        env:
          DISTINCT_ID: ${{ github.event.inputs.distinct_id }}
        run: echo "$DISTINCT_ID"

      - name: Test Expected Inputs
        env:
          BRANCH: ${{ inputs.branch }}
          INFRA_LIVE_REPO: ${{ inputs.infra_live_repo }}
          WORKING_DIRECTORY: ${{ inputs.working_directory }}
          TERRAGRUNT_COMMAND: ${{ inputs.terragrunt_command }}
          MANAGEMENT_ACCOUNT: ${{ inputs.management_account }}
          NEW_ACCOUNT_NAME: ${{ inputs.new_account_name }}
          PRESIGNED_CALLER_IDENTITY: ${{ inputs.presigned_caller_identity }}
        run: |
          # Required Inputs
          echo "BRANCH: $BRANCH"
          echo "INFRA_LIVE_REPO: $INFRA_LIVE_REPO"
          echo "WORKING_DIRECTORY: $WORKING_DIRECTORY"
          echo "TERRAGRUNT_COMMAND: $TERRAGRUNT_COMMAND"
          echo "MANAGEMENT_ACCOUNT: $MANAGEMENT_ACCOUNT"
          echo "NEW_ACCOUNT_NAME: $NEW_ACCOUNT_NAME"

          if [[ ${PRESIGNED_CALLER_IDENTITY:-} != "fake token" ]]; then
            echo "Did not receive expected presigned caller identity"
            exit 1
          fi
