name: TEST Create SDLC Accounts and Generate Baseline PR

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        description: "A distinct ID for this workflow run"
        required: true
        type: string
      branch:
        description: "The branch in the infrastructure-live repo in which to run the command"
        required: true
        type: string
      working_directory:
        description: "The folder path in which terragrunt will execute"
        required: true
        type: string
      management_account:
        description: "The AWS Account ID of the Control Tower Management Account"
        required: true
        type: string
      terragrunt_command:
        type: string
        description: "The terragrunt command to run"
        required: true
        default: "plan"
      infra_live_repo:
        type: string
        description: "The infrastructure live repo on which to run terragrunt"
        required: true
      team_account_names:
        type: string
        description: "The names of the team accounts to create"
        required: true
      presigned_caller_identity:
        description: "The presigned URL sent by the calling account"
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        env:
          DISTINCT_ID: ${{ github.event.inputs.distinct_id }}
        run: echo "$DISTINCT_ID"
      - name: Test Expected Inputs
        env:
          BRANCH: ${{ inputs.branch }}
          INFRA_LIVE_REPO: ${{ inputs.infra_live_repo }}
          WORKING_DIRECTORY: ${{ inputs.working_directory }}
          TERRAGRUNT_COMMAND: ${{ inputs.terragrunt_command }}
          MANAGEMENT_ACCOUNT: ${{ inputs.management_account }}
          TEAM_ACCOUNT_NAMES: ${{ inputs.team_account_names }}
          PRESIGNED_CALLER_IDENTITY: ${{ inputs.presigned_caller_identity }}
        run: |
          # Required Inputs
          echo "BRANCH: $BRANCH"
          echo "INFRA_LIVE_REPO: $INFRA_LIVE_REPO"
          echo "WORKING_DIRECTORY: $WORKING_DIRECTORY"
          echo "TERRAGRUNT_COMMAND: $TERRAGRUNT_COMMAND"
          echo "MANAGEMENT_ACCOUNT: $MANAGEMENT_ACCOUNT"
          echo "TEAM_ACCOUNT_NAMES: $TEAM_ACCOUNT_NAMES"

          if [[ -z ${PRESIGNED_CALLER_IDENTITY:-} ]]; then
            echo "PRESIGNED_CALLER_IDENTITY is not set"
            exit 0
          fi

          if [[ ${PRESIGNED_CALLER_IDENTITY} != "fake token" ]]; then
            echo "Did not receive expected presigned caller identity"
            exit 1
          fi
