name: TEST Pipelines Execute
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch in the infrastructure-live repo in which to run the command"
        required: true
        type: string
      working_directory:
        description: "The folder path in which the command will run"
        required: true
        type: string
      account:
        description: "The AWS Account ID of the ultimate account we will take action on"
        required: true
        type: string
      terragrunt_command:
        type: string
        description: "The terragrunt command to run"
        required: true
        default: "plan"
      infra_live_repo:
        type: string
        description: "The infrastructure live repo on which to run terragrunt"
        required: true
      pipelines_change_type:
        type: choice
        description: The change type for the infra change, as detected by pipelines orchestrate
        required: true
        options:
          - ModuleChanged
          - ModuleDeleted
          - ModuleAdded
          - ModulesAdded
          - EnvCommonChanged
          - EnvCommonDeleted
          - EnvCommonAdded
          - AccountRequested
          - AccountAdded
          - AccountChanged
          - PipelinesPermissionAdded
          - PipelinesPermissionChanged
          - PipelinesPermissionDeleted
          - PipelinesEnvCommonPermissionAdded
          - PipelinesEnvCommonPermissionChanged
          - PipelinesEnvCommonPermissionDeleted
      child_account_id:
        description: "The AWS Account ID of the child account"
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Expected Inputs
        env:
          BRANCH: ${{ inputs.branch }}
          INFRA_LIVE_REPO: ${{ inputs.infra_live_repo }}
          WORKING_DIRECTORY: ${{ inputs.working_directory }}
          TERRAGRUNT_COMMAND: ${{ inputs.terragrunt_command }}
          ACCOUNT: ${{ inputs.account }}
          PIPELINES_CHANGE_TYPE: ${{ inputs.pipelines_change_type }}
          CHILD_ACCOUNT_ID: ${{ inputs.child_account_id }}
        run: |
          # Required Inputs
          echo "BRANCH: $BRANCH"
          echo "INFRA_LIVE_REPO: $INFRA_LIVE_REPO"
          echo "WORKING_DIRECTORY: $WORKING_DIRECTORY"
          echo "TERRAGRUNT_COMMAND: $TERRAGRUNT_COMMAND"
          echo "ACCOUNT: $ACCOUNT"
          echo "PIPELINES_CHANGE_TYPE: $PIPELINES_CHANGE_TYPE"
          echo "CHILD_ACCOUNT_ID: ${CHILD_ACCOUNT_ID:-}"
