name: Test Trigger Workflow

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        change_type:
            - ModuleChanged
            - ModuleDeleted
            - ModuleAdded
            - ModulesAdded
            - EnvCommonChanged
            - EnvCommonDeleted
            - EnvCommonAdded
            - AccountRequested
            - TeamAccountsRequested
            - AccountAdded
            - TeamAccountsAdded
            - AccountChanged
            - PipelinesPermissionAdded
            - PipelinesPermissionChanged
            - PipelinesPermissionDeleted
            - PipelinesEnvCommonPermissionAdded
            - PipelinesEnvCommonPermissionChanged
            - PipelinesEnvCommonPermissionDeleted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get branch name
        id: branch
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Trigger action.yml workflow
        uses: "./"
        with:
          account_id: "123"
          repo: pipelines-dispatch
          repo_owner: gruntwork-io
          branch: ${{ steps.branch.outputs.branch }}
          working_directory: "."
          command: "command"
          args: "args"
          infra_pipelines_token: ${{ secrets.GITHUB_TOKEN }}
          infra_live_token: ${{ secrets.GITHUB_TOKEN }}
          change_type: ${{ matrix.change_type }}
          additional_data: "additional_data"
          actor: "actor"
